[book]
authors = ["wbigger"]
language = "it"
multilingual = false
src = "src"
title = "Sistemi e Reti - 4y"

[output.html]
additional-css = ["custom.css"]
git-repository-url = "https://github.com/wbigger/book-4y-networks/"
